# site settings

title: Samyak Jain
description: Online resume
taglong: A budding financier
tagshort: financier
url: https://sj-samyakjain.github.io/
baseurl: ""
permalink: pretty
repo: https://github.com/sj-samyakjain/sj-samyakjain.github.io

# author settings

author:
  name: Place Holder
  email: jsamm291@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  # facebook: username
  # github: username
  # instagram: username
  linkedin: jsamm291
  # stackoverflow: 0000000/username
  # twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
